name = "Denizen's Delight"
author = "SwankyDenizen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a16b497705a79419dec04201d989ff01e8b209990a4d734ab38e0f617df1bb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
