name = "Denizen's Delight"
author = "SwankyDenizen"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "172b2689bc0cd8bedf74f29e5d3d7b96863099cecebeaac9f7c9e91439363ec3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
