name = "Denizen's Delight"
author = "SwankyDenizen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2faefdd96b135d1ec7b6beaa14d25d41fe51744e35185a5cd7113a7b46a1c1ab"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
