# If false, the item's durability won't change upon death.
DegradeEquipmentOnDeath: true
# If DegradeEquipmentOnDeath is enabled: Saved items will degrade by 0.10, meaning 10%.
DegradePercentage: 0.1
# Keep all item in the hot bar, only the currently selected item is kept if this value is false.
KeepHotbarItemsOnDeath: false
# Keep player experience on death
KeepXpOnDeath: false
# How much of the experience should be kept. 0.9 means 90%
KeptXpPercentage: 0.9
