#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Feb 02 16:45:07 EST 2026
alwaysLogTamperWarnings=false
